name: Create Release Branch

on:
  schedule:
    - cron: '0 23 * * 0'

jobs:
  create_release_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Get Current Time
        uses: 1466587594/get-current-time@v1.0.0
        id: current-time
        with:
          format: YYMMDD
          utcOffset: "+05:00"
      - name: Create Release Branch
        uses: peterjgrainger/action-create-branch@v1.0.0
        id: create_release_branch
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'Release-v${{ steps.current-time.outputs.formattedTime }}'
      - uses: actions/checkout@v2.1.0
      - name: Push Tag
        uses: aaiezza/create-release@master
        id: push_tag
        with:
          tag: 'v${{ steps.current-time.outputs.formattedTime }}'
          release_branch: 'Release-v${{ steps.current-time.outputs.formattedTime }}'
          create_release: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
